### ISSUE TITLE
How to check current query size to split many bulk insertion queries?

### ISSUE THREAD

**Issue by peter279k** [softmetrix/BulkInsertBuilder#1]
As title, I need to know current query size and I can split current size with bulk insertion builder.

And it will let me avoid getting ` Got a packet bigger than 'max_allowed_packet' bytes` error message.

Is it possible to implement this feature?

**Comment by mmedojevicbg** [comment]
Hi,
Current split size is 1000 records by default. It can be adjusted by passing parameter to constructor. 
For example, if you need 2000 split size:
`$bulkInsertBuilder = new BulkInsertBuilder($dsn, $username, $password, $table, 2000);`

**Comment by peter279k** [comment]
Hi, thanks for your reply.

I need to have following feature:

When I use specific bulk records, the builder can get the max allowed packet size.

And check whether this bulk record can be inserted without getting packet is bigger than max packet size error message.

@mmedojevicbg. Is it possible to be implemented?

**Comment by peter279k** [comment]
My question is very similar with [this](https://stackoverflow.com/questions/37203632/how-to-check-the-current-query-packet-size-for-mysql), but it seems that using `strlen` cannot get current query size to compare to max allowed packet size.

**Comment by peter279k** [comment]
I have got current answer on this [issue](https://github.com/brick/db/issues/6).

It's hard to implement this issue and the current way is to calculate query size and compare to half length of `max_allowed_packet` size. And generate safe bulk insertion queries :).

**Comment by mmedojevicbg** [comment]
BulkInsertBuilder is still in development phase (v 0.1). We are currently researching max_allowed_packet issue. 
Thanks for helping us improve library. We will let you know as soon as we find solution.
